-------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow-app
  labels:
    app: tensorflow-app
spec:
  selector:
    matchLabels:
      app: tensorflow-app
  template:
    metadata:
      labels:
        app: tensorflow-app
    spec:
      containers:
      - name: tf-serving-digit-classification
        image: tensorflow/serving
        ports:
          - containerPort: 8501
        args:
          - --rest_api_port=8501
          - --model_name=digit_classify
          - --model_base_path=/config/models/digit_classify
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: configmap
-------------------
