-------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow-app
  labels:
    app: tensorflow-app
spec:
  selector:
    matchLabels:
      app: tensorflow-app
  template:
    metadata:
      labels:
        app: tensorflow-app
    spec:
      containers:
      - name: tf-serving-digit-classification
        image: tensorflow/serving
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: configmap
-------------------
