-------------------
apiVersion: apps/v1
kind: Deployment
namespace: tensorflow-serving
metadata:
  name: tensorflow-app
  labels:
    app: tensorflow-app
spec:
  selector:
    matchLabels:
      app: tensorflow-app
  template:
    metadata:
      labels:
        app: tensorflow-app
    spec:
      containers:
      - name: tf-serving-digit-classification
        image: tensorflow/serving
        ports:
          - containerPort: 8501
        args:
          - --rest_api_port=8501
          - --model_name=digit_classify
          - --model_base_path=/config/models/digit_classify
          - --monitoring_config_file=/config/metrics.config
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: configmap
-------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: tensorflow-serving
  labels:
    app: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--config.file=/config/prometheus.yaml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /config
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: config
          configMap:
            name: configmap 
        - name: prometheus-storage-volume
          emptyDir: {}

