apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
    - name: configmap
      files:
        - metrics.config
        - batch.config
      namespace: "tensorflow"
resources:
    - deployment.yaml
    - service.yaml
