-------------------
apiVersion: apps/v1
kind: Service
metadata:
  name: tensorflow-app
  labels:
    run: tensorflow-app
spec:
  ports:
    - port: 5050
      targetPort: 8501
  selector:
    run: tensorflow-app
  
-------------------
