-------------------
apiVersion: apps/v1
kind: Service
metadata:
  namespace: tensorflow-serving
  name: tensorflow-app
  labels:
    run: tensorflow-app
spec:
  ports:
    - port: 5050
      targetPort: 8501
  selector:
    run: tensorflow-app
-------------------
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: tensorflow-serving
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
  
spec:
  selector: 
    app: prometheus-server
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 9090 
      nodePort: 30000
