-------------------
apiVersion: apps/v1
kind: Service
metadata:
  name: tensorflow-service
  labels:
    run: tensorflow-service
spec:
  ports:
    - port: 80
  selector:
    run: tensorflow-service
  
-------------------
